"""empty message

Revision ID: 8f72eb3c8c54
Revises: 
Create Date: 2026-02-21 12:56:42.831528

"""
from alembic import op#type: ignore
import sqlalchemy as sa #type: ignore


# revision identifiers, used by Alembic.
revision = '8f72eb3c8c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
